version: "3"

services:
  postgres:
    image: library/postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  snowflake:
    image: docker.pkg.github.com/lukeshay/snowflake/scratch:5008c5afbd04bf3fb689a786be545b2c188831e9
    environment:
      NODE_ID: 1
    ports:
      - "8080:8080"