version: "3"

services:
  postgres:
    image: library/postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  snowflake:
    image: docker.pkg.github.com/lukeshay/snowflake/scratch:07cb06a36b58e627bb43de5b3bb3e50228dc612a
    environment:
      NODE_ID: 1
    ports:
      - "8080:8080"