name: Actions
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make build
      - run: make push
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: jeffrey-krueger-dev
          heroku_email: "shay.luke17@gmail.com"
      - if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#00FF00"
          args: "Deployed ${{ github.sha }} to jeffrey-krueger-dev"
      - if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#FF0000"
          args: "Failed to deploy ${{ github.sha }} to jeffrey-krueger-dev"
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: jeffrey-krueger-staging
          heroku_email: "shay.luke17@gmail.com"
      - if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#00FF00"
          args: "Deployed ${{ github.sha }} to jeffrey-krueger-staging"
      - if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#FF0000"
          args: "Failed to deploy ${{ github.sha }} to jeffrey-krueger-staging"
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: jeffrey-krueger-prod
          heroku_email: "shay.luke17@gmail.com"
      - if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#00FF00"
          args: "Deployed ${{ github.sha }} to jeffrey-krueger-prod"
      - if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#FF0000"
          args: "Failed to deploy ${{ github.sha }} to jeffrey-krueger-prod"