name: Actions
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make build
      - run: make push
  deploy-dev:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew deployHeroku --stacktrace --debug
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#00FF00"
          args: "Deployed ${{ github.sha }} to jeffery-krueger-dev"
      - if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#FF0000"
          args: "Failed to deploy ${{ github.sha }} to jeffery-krueger-dev"