name: Actions
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make build
      - run: make push
      - if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "jeffrey-krueger-dev"
          heroku_email: "shay.luke17@gmail.com"
      - if: github.ref == 'refs/heads/master'
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          args: Deployed ${GITHUB_REF} to DEVELOPMENT